language: java
jdk: openjdk16

os:
  - linux
  - osx

script:
  - wget https://github.com/forax/java-next/releases/download/untagged-4890d0aa579cf85dd353/jdk-16-loom-linux.tar.gz
  - tar -xzf jdk-16-loom-linux.tar.gz
  - export JAVA_HOME=$HOME/jdk-16-loom
  - mvn package

